---
title: "Energy"
author: "Nora Stanley"
date: "2026-02-10"
output: html_document
---
##Renewable Energy Dataset
```{r,fig.height=7,fig.width=10}
library(readr)
library(dplyr)
library(ggplot2)
library(plotly)
library(ggthemes)
energy<-read_csv('../../data/IRENA data.csv', skip=1)

energy_2<-energy%>%
  rename(country='Country/area')

high_gdp<-c("United States","Qatar","Norway","Singapore","United Arab Emirates",
            "Switzerland","Ireland","Luxembourg","Saudi Arabia","Taiwan")
low_gdp<-c("Burundi","Central Africa Republic","Liberia","Democratic Republic of Congo",
           "Mozambique","Niger","Madagascar","Malwai","Chad","Afghanistan")
energy_2$`Electricity statistics`<-
  as.numeric(gsub("-",NA,energy_2$`Electricity statistics`))
world<-energy_2%>%
  group_by(Technology,`Data Type`,`Grid connection`,Year)%>%
  summarise(`Electricity statistics`=sum(`Electricity statistics`,na.rm=TRUE),
            .groups="drop")%>%
  mutate('country'="World")
energy_2<-bind_rows(energy_2,world)

energy_groups<-energy_2%>%
  mutate(group=case_when(
    country=="World"~"World",
    country%in%high_gdp~"High GDP",
    country %in%low_gdp~"Low GDP",
    TRUE~NA_character_))%>%
  filter(!is.na(group))
energy_groups_sdg<-energy_groups%>%
  filter(Year%in% c(2012,2023))
energy_groups_sdg<-energy_groups_sdg%>%
  group_by(group,Year,Technology)%>%
  summarise(total=sum(`Electricity statistics`, na.rm=TRUE),
            .groups="drop")
energy_groups_no_total<-energy_groups_sdg%>%
  filter(!Technology%in%c("Total renewable","Total non-renewable","Total"))

energy_graph<-ggplot(energy_groups_no_total,
       aes(x=group,
           y=total,
           fill=Technology))+
  geom_col(position="fill",size=0.01)+
  scale_y_continuous(labels=scales::percent)+
  facet_wrap(~Year)+
  coord_flip()+
labs(title="Energy Breakdown for Developed and Developing Countries",
     x="Development Status of Countries",
     y="Percent of Energy Type")+
  theme_dark()
ggplotly(energy_graph)

```

## Gapminder Dataset
```{r}
library(gapminder)
library(dplyr)
library(ggplot2)
data(gapminder)
gapminder%>%head
gap<-gapminder%>%
  filter(country %in% c('United States', 'China', 'France','Liberia','Ethiopia','Haiti'))%>%
  filter(year>1970) %>% 
  mutate(status = ifelse(country %in% c('United States', 'China', 'France'), 'Developed', 'Developing'))

ggplot(gap,
       aes(x=year, 
           y=lifeExp,
           color=country,
           linetype=status)) +
  geom_line(size=1, alpha=0.5)+
 #scale_linetype_manual(values=c("China"="solid","France"="solid","United States"="solid",
  #                     "Ethiopia"="dashed","Haiti"="dashed","Liberia"="dashed")) +
  labs(title = "Life Expectancy for Developed and Undeveloped Countries Over Time",
  x = "Year",
  y = "Life Expectancy")+
  theme_clean()

```

##Carbon emmissions
```{r}
library(dplyr)
library(readr)
library(ggplot2)
library(plotly)
library(ggthemes)
url <-'https://nyc3.digitaloceanspaces.com/owid-public/data/co2/owid-co2-data.csv'
carbon <-
  read_csv(url) 
carbon<-carbon%>%
  mutate(gdp_per_capita=gdp/population)
high_gdp<-c("United States","Qatar","Norway","Singapore","United Arab Emirates",
            "Switzerland","Ireland","Luxembourg","Saudi Arabia","Taiwan")
low_gdp<-c("Burundi","Central Africa Republic","Liberia","Democratic Republic of Congo",
           "Mozambique","Niger","Madagascar","Malwai","Chad","Afghanistan")
carbon_groups<-carbon%>%
  mutate(group=case_when(
    country=="World"~"World",
    country%in%high_gdp~"High GDP",
    country %in%low_gdp~"Low GDP",
    TRUE~NA_character_))%>%
  filter(!is.na(group))

carbon_wo_world<-carbon%>%
  filter(country!="World")
carbon_groups<-carbon_wo_world%>%
  mutate(group=case_when(
    country%in%high_gdp~"High GDP",
    country%in%low_gdp~"Low GDP",
    TRUE~"World"))
carbon_trend<-carbon_groups%>%
  group_by(year,group)%>%
  summarise(mean_temp=mean(temperature_change_from_ghg, na.rm=TRUE),
            .groups="drop")
plot_1<-ggplot(carbon_trend,
       aes(x=year,y=mean_temp,color=group))+
  geom_line(size=1)+
  geom_vline(xintercept=2012,
             linetype ="dashed",
             size=0.5)+
    scale_x_continuous(limits=c(1850,max(carbon_trend$year)))+
  labs(title="Average Temperature Change from Greenhouse Gas Emmissions",
       x="Year",
       y="Temperature Change",
       color="Key")+
  labs(title="Average emperature Change from Greenhouse Gas Emmissions",
       x="Temperature Change from Gas Emmissions",
       y="Development of Countries")+
  annotate(geom='text',
           x=1985,
           y=.005,
           size=3,
           label='Year when SDGs
     were created')+
  theme_minimal()

 #TEMP CHANGE FROM GHGS

```

```{r}
library(dplyr)
library(readr)
library(ggplot2)
library(plotly)
library(ggthemes)
url <-'https://nyc3.digitaloceanspaces.com/owid-public/data/co2/owid-co2-data.csv'
carbon <-
  read_csv(url)

carbon_groups<-carbon%>%
  mutate(group=case_when(
    country=="World"~"World",
    country%in%high_gdp~"High GDP",
    country %in%low_gdp~"Low GDP",
    TRUE~NA_character_))%>%
  filter(!is.na(group))

high_gdp<-c("United States","Qatar","Norway","Singapore","United Arab Emirates",
            "Switzerland","Ireland","Luxembourg","Saudi Arabia","Taiwan")
low_gdp<-c("Burundi","Central Africa Republic","Liberia","Democratic Republic of Congo",
           "Mozambique","Niger","Madagascar","Malwai","Chad","Afghanistan")
carbon_wo_world<-carbon%>%
  filter(country!="World")

carbon_groups<-carbon_wo_world%>%
  mutate(group=case_when(
    country%in%high_gdp~"High GDP",
    country%in%low_gdp~"Low GDP",
    TRUE~"World"))
carbon_trend<-carbon_groups%>%
  group_by(year,group)%>%
  summarise(mean_temp=mean(temperature_change_from_ghg, na.rm=TRUE),
            .groups="drop")
plot_2<-ggplot(carbon_trend,
       aes(x=year,y=mean_temp,color=group))+
  geom_line(size=1)+
  geom_vline(xintercept=2012,
             linetype ="dashed",
             size=0.5)+
    scale_x_continuous(limits=c(2000,max(carbon_trend$year)))+
  labs(title="Average Temperature Change from Greenhouse Gas Emmissions",
       x="Year",
       y="Temperature Change",
       color="Key")+
  annotate(geom='text',
           x=2008,
           y=0.005,
           size=3,
           label='Year when SDGs
     were created')+
  theme_minimal()
```

```{r,fig.height=5,fig.width=11}
library(ggpubr)
ggarrange(plot_1,plot_2,nrow=1)+
  labs(title="Average Temperature Change from Greenhouse Gases from Developed and Developing Countries")

```

##Levelized cost of energy
```{r}
library(readr)
url <- 'https://raw.githubusercontent.com/ericmkeen/sewanee_esus/master/02_energy_sector/levelized-cost-of-energy.csv'
econ <- read_csv(url)
econ%>%head



```


```{r}
library(ggplot2)
library(dplyr)
library(readr)
library(ggthemes)
url <- 'https://raw.githubusercontent.com/ericmkeen/sewanee_esus/master/02_energy_sector/levelized-cost-of-energy.csv'
econ <- read_csv(url)
#cost of renewable and non-renewable sources
econ_filtered<-econ%>%
  filter(country%in% c("United States","France","Sweden","Germany","Japan","China","South Korea","United Kingdom","Netherlands","Denmark"))
            
p<-ggplot(econ_filtered,
       aes(x=year,
           y=cost,
           color=factor(source),
           text=paste("country:",country,
                      "<br>year:",year,
                      "<br>source:",source,
                      "<br>cost:",round(cost,2))))+
  geom_point()+
  geom_vline(xintercept=2012)+
  labs(title="Cost and Use of Energy Types for Developed Countries",
       x="Year",
       y="Cost",
       color="Energy Source")
  annotate(geom='text',
           x=2003,y=0.52,
           size=3,
           label='Year when SDGs were created')
  
ggplotly(p,tooltip="text")

```

```{r}
library(dplyr)
library(knitr)
econ_filtered<-econ%>%
  filter(country%in% c("United States","France","Sweden","Germany","Japan","China","South Korea","United Kingdom","Netherlands","Denmark"))
econ_filtered%>%
  group_by(year,country)%>%
  summarize(cost=mean(cost, na.rm=TRUE))%>%
  kable
```


